// Phase 6 checkpoint + offline training: evolve a single-pole neural controller,
// assert it beats a balance-fitness threshold, verify it actually holds upright,
// and (when run with --save) write the champion as a JS module the app ships.

import { evolve } from '../src/lib/evolve/ga.js'
import { makeRollout } from '../src/projects/pendulum/neural/rollout.js'
import { policyForce } from '../src/projects/pendulum/neural/policy.js'
import * as single from '../src/projects/pendulum/plants/single.js'
import fs from 'fs'

const roll = makeRollout(single)
const t0 = Date.now()
const { best, history } = evolve({
  paramCount: roll.paramCount, randomParams: roll.randomParams, mutate: roll.mutate, evaluate: roll.evaluate,
  pop: 80, gens: 120, elite: 6, tournamentK: 4, mut: { rate: 0.15, strength: 0.35 },
  onProgress: ({ gen, best, avg }) => { if (gen % 20 === 0) console.log(`  gen ${gen}: best=${best.toFixed(3)} avg=${avg.toFixed(3)}`) },
})
console.log(`evolved in ${((Date.now() - t0) / 1000).toFixed(1)}s — champion fitness ${best.fitness.toFixed(3)} (gen ${best.gen})`)

// Verify: from hanging, does the champion swing up and hold near upright?
const dt = 1 / 120
let s = single.initialState()
let upFrac = 0
const steps = Math.round(12 / dt)
for (let i = 0; i < steps; i++) {
  let f = policyForce(roll.mlp, best.weights, single, s)
  f = Math.max(-single.PARAMS.forceMax, Math.min(single.PARAMS.forceMax, f))
  s = single.step(s, f, dt)
  if (i > steps / 2 && Math.abs(single.wrapPi(s.theta)) < 0.35) upFrac++
}
upFrac /= (steps / 2)
console.log(`from hanging: final theta=${single.wrapPi(s.theta).toFixed(3)}, upright fraction (2nd half)=${(upFrac * 100).toFixed(0)}%`)

const balanced = best.fitness > 3.0 && upFrac > 0.6
console.log(balanced ? 'PASS: champion learned to reach & hold upright' : 'FAIL: champion did not learn')

if (process.argv.includes('--save') && balanced) {
  const out = `// Auto-generated by scratchpad/train-single.mjs — pre-trained neural champion.
// Evolved via neuroevolution (see src/lib/evolve). Loaded so the neural
// controller works instantly; users can retrain live in the browser.
export const CHAMPION = {
  arch: [${roll.mlp.arch.join(', ')}],
  fitness: ${best.fitness.toFixed(4)},
  weights: [${Array.from(best.weights).map(w => w.toFixed(5)).join(', ')}],
}
`
  fs.writeFileSync('src/projects/pendulum/neural/champion-single.js', out)
  console.log('saved -> src/projects/pendulum/neural/champion-single.js')
}
process.exit(balanced ? 0 : 1)
